[package]
name = "flags"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.24.2"
miniquad = "0.3.16"
quad-rand = "0.2.1"
rayon = "1.8.0"

[profile.release]
debug = true
